# Generated by Django 6.0.1 on 2026-02-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('exchange', models.CharField(max_length=10)),
                ('ticker_symbol', models.CharField(max_length=20, unique=True)),
                ('issue_open_date', models.DateField()),
                ('issue_close_date', models.DateField()),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('price_band_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_band_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lot_size', models.IntegerField()),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['issue_open_date'], name='ipos_ipo_issue_o_f17815_idx'), models.Index(fields=['issue_close_date'], name='ipos_ipo_issue_c_1bb37c_idx')],
            },
        ),
    ]
