# Generated by Django 6.0.1 on 2026-01-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    ''' check  '''

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=20)),
                ('exchange', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE'), ('BOTH', 'Both')], max_length=10)),
                ('price_band_low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_band_high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_size_crores', models.DecimalField(decimal_places=2, max_digits=12)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('underwriters', models.TextField(blank=True)),
                ('revenue_crores', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ebitda_crores', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pat_crores', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ebitda_margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pat_margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('roce_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('debt_to_equity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pe', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('valuation_comment', models.TextField(blank=True)),
                ('business_description', models.TextField(blank=True)),
                ('geography_focus', models.CharField(blank=True, max_length=200)),
                ('management_summary', models.TextField(blank=True)),
                ('competitor_analysis', models.TextField(blank=True)),
                ('usp', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
