# Generated by Django 6.0.1 on 2026-02-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnew', '0002_add_min_qty_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipo',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
